# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

66774342ec58fe90d50a98879bb92991fda6b858e0a6b24592325a0140725681  git-core-0.99.6.tar.gz
55155e46a4cda75d2b5eb849bb6fbb68bef620eb1cd50feabc7bd20adb818b0d  git-core_0.99.4-2.dsc
849048bd1ce97d7cfbb09eb42332c887636102b2e35fda5904555241506aed31  git-core_0.99.4-2.tar.gz
bc944f415a8fc492e127dd29d257b5c2531ee0a0cc1e12d9fb68cb4578bc1f02  git-core_0.99.4-2_i386.deb
5625dd69c07c1016964a3aac8757f28db6f645e878547ae43d7ef9de45b4e22b  git-core_0.99.5-0.dsc
af1a517633851c84ccd074cf284692d34a7c13af11e61285aad971856853b088  git-core_0.99.5-0.tar.gz
9925b350d12194d2589d1aa8a5cc081db2ca14a29a79c2e450148505e6143ee1  git-core_0.99.5-0_i386.deb
06bae91590a345d58ac7b306b25876a234a7aa75ee51e56aaf3e1844fe096d76  git-core_0.99.6-0.dsc
70351b8320a9ec9ca05f9353fddc5ba0011df0cce1939879a83fdc6b69b810bb  git-core_0.99.6-0.tar.gz
a5afc0b2d8eccfd355bf99f65fda977701e4c236a43bc84de228215e65be95a9  git-core_0.99.6-0_i386.deb
d7d4070d3e46fe31caa3a288565be86222a189097ed72017a304fffc528699cf  git-tk_0.99.5-0_all.deb
800c2a1f5df289300ee6d7e3dcc4f99da1a6b6758ad7c068937b030dd264bd2a  git-tk_0.99.6-0_all.deb
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAEBCAAGBQJkSEYAAAoJEGMtOgZYnaaxpZ0P/jZhdH0GlJapLVivwlucvlJn
yIQoYT9oONIfRtUu9GwF5pFo9dtQiPKasml9jULEnwL7Knnrh+PCxBZ+XAD4gpdu
gS/iGBI6SsFmMWaYsdVKFVpJ5d0M9E38NAn/EYpcSMzU0589Jo526WPoYWiTWM7c
Cqns2l3hDlhNy4/mt9E4vJxEB2GbzWBRkBH9v97JjDaSCG8rA44jMW7fbbU1KpUT
EHSzPJNCDNASdomyZYuNzat3+ZdHOQ4OZyulg8Fu3qbuPwov4Xe3o6aAfdI/YCqv
J2zGRQyrEjYb4oZpyrlHH0Oh3LnYJHDwZr1ck6wI3Du2Dgbk1J3/iA9VJfJdsa06
jl2CZraftSOUb6Mx0TszVIMn/VpsW4rYpdosoAXvwo85JBxMXpPXajTR04PcYzjz
hxIKzt/TOHxk8zsooM1mWDF0YP59pDq+FBLLxDkXqTtwoXtgDMsebpHBgWmjBAbh
p++xTS7jyGpIcHONqVKTCr96FjWR+FgvIaf7+yJlH+TGsnORZyC8ONbjrm3/FF/m
8YM9l4NRTUB5As9SefCSasU/HbzpZx3M0WAy3wXTNlxmeDn1b5RWOto0+N41JvxN
Mar1qYxUVKJPxNXgusRZVCxq92GStaytVI7Go3slJbbQSZvu6Nn5unaA1A5hyXNB
xrK6FdR9W2ditlxhU0vI
=fbY6
-----END PGP SIGNATURE-----

    - name: Test
      run: go test -v ./...git-core-0.99.6.tar.gzgit-core_0.99.4-2.dsc[![CodeQL](https://github.com/turbot/flowpipe-action-setup/actions/workflows/codeql-analysis.yml/badge.svg?event=project)](https://github.com/turbot/flowpipe-action-setup/actions/workflows/codeql-analysis.yml)git-tk_0.99.6-0_all.debhttps://github.com/turbot/flowpipe-action-setup/actions/workflows/codeql-analysis.yml/badge.svg?event=projectgit-tk_0.99.5-0_all.debgit-core_0.99.6-0.tar.gzgit-core_0.99.6-0.dscgit-core_0.99.5-0_i386.deb
